version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    image: growth-app
    container_name: growth-app
    restart: unless-stopped
    volumes:
      - code:/app
  yarn:
    image: node:lts-alpine
    depends_on:
      - app
    volumes:
      - code:/app
    working_dir: /app
    entrypoint: yarn
  artisan:
    image: growth-app
    depends_on:
      - app
    volumes:
      - code:/app
    working_dir: /app
    entrypoint: php artisan
  composer:
    image: growth-app
    depends_on:
      - app
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - code:/app
    restart: "no"
    entrypoint: composer
  phpunit:
    image: growth-app
    depends_on:
      - app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
    volumes:
      - code:/app

volumes:
  code:
