version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    image: growth-app
    container_name: growth-app
    restart: unless-stopped
    volumes:
      - code:/app
  yarn:
    image: node:lts-alpine
    depends_on:
      - app
    volumes:
      - code:/app
    working_dir: /app
    entrypoint: yarn
  artisan:
    image: growth-app
    depends_on:
      - app
    volumes:
      - code:/app
    working_dir: /app
    entrypoint: php artisan
  composer:
    image: growth-app
    depends_on:
      - app
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - code:/app
    restart: "no"
    entrypoint: composer
  phpunit:
    image: growth-app
    depends_on:
      - app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
    volumes:
      - code:/app

  web-app:
    build:
      args:
        user: www-data
        uid: 1000
      context: ./
      dockerfile: docker/web-app/Dockerfile
    image: growth-web
    container_name: growth-web-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - growth-web

  db:
    image: mysql:5.7
    container_name: growth-web-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - growth-web

  nginx:
    image: nginx:alpine
    container_name: growth-web-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - growth-web

networks:
  growth-web:
    driver: bridge

volumes:
  code:
