version: '3'
services:
  yarn:
    image: node:lts-alpine
    volumes:
      - code:/app
    working_dir: /app
    entrypoint: yarn

  artisan:
    image: growth-web
    depends_on:
      - web-app
    volumes:
      - code:/app
    working_dir: /app
    networks:
      - growth-web
    entrypoint: php artisan

  composer:
    image: growth-web
    depends_on:
      - web-app
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    restart: "no"
    volumes:
      - code:/app
    working_dir: /app
    entrypoint: composer

  phpunit:
    image: growth-web
    depends_on:
      - web-app
    volumes:
      - code:/var/www
    entrypoint: vendor/bin/phpunit

  web-app:
    build:
      args:
        user: mogo
        uid: 1000
      context: ./
      dockerfile: docker/web-app/Dockerfile
    image: growth-web
    container_name: growth-web-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - code:/var/www
    networks:
      - growth-web

  db:
    image: mysql:5.7
    container_name: growth-web-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - growth-web

  nginx:
    image: nginx:alpine
    container_name: growth-web-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - code:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - growth-web

  files:
    image: alpine:latest
    container_name: growth-web-files
    entrypoint: top
    restart: unless-stopped
    volumes:
      - code:/app

networks:
  growth-web:
    driver: bridge

volumes:
  code:
