version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: docker/api/Dockerfile
    image: api
    container_name: growth-app
    restart: unless-stopped
    volumes:
      - code:/app
  yarn:
    image: node:lts-alpine
    depends_on:
      - api
    volumes:
      - code:/app
    working_dir: /app
    entrypoint: yarn
  artisan:
    image: api
    depends_on:
      - api
    volumes:
      - code:/app
    working_dir: /app
    entrypoint: php artisan
  composer:
    image: api
    depends_on:
      - api
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - code:/app
    restart: "no"
    entrypoint: composer
  phpunit:
    image: api
    depends_on:
      - api
    working_dir: /app
    entrypoint: vendor/bin/phpunit
    volumes:
      - code:/app

volumes:
  code:
