name: deploy
on:
  push:
    branches:
      - master
      - '**'
jobs:
  tests:
    uses: './.github/workflows/test.yml'
  build:
    name: build
    needs: [ tests ]
    runs-on: ubuntu-latest

    steps:
      - name: SCP project into test folder on server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: github
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./*"
          target: "test"
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: github
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: whoami
