name: GitHub Actions Demo
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: make something
        run: mkdir foobar
      - run: touch ./foobar/helloworld.txt
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./foobar/*
          host: ${{ secrets.SSH_HOST }}
          remote: /home/github/test/
          port: 22
          user: github
          key: ${{ secrets.SSH_PRIVATE_KEY }}
